// <auto-generated />
using System;
using Efcore.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ef_core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Size")
                        .HasPrecision(15, 2)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drinks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coffee",
                            Price = 1000m,
                            Size = "Large"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tea",
                            Price = 2000m,
                            Size = "XLarge"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Juice",
                            Price = 1500m,
                            Size = "XXLarge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Water",
                            Price = 1200m,
                            Size = "Medeuim"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Smoothie",
                            Price = 3000m,
                            Size = "Small"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Foods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = " Falafel",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fish",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Makloba",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sushi",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Homos",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Errors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
